import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import {
  ClerkLoaded,
  ClerkLoading,
  ClerkProvider,

} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
   
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           
           <ClerkLoading>
              <div>Clerk is loading...</div>
            </ClerkLoading>
            <ClerkLoaded>
              {children}
            </ClerkLoaded>
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
